#!/usr/bin/env python3
import re, datetime

with open('index.html','r',encoding='utf-8') as f: html = f.read()

c = r'''  <div class="section-gap section-indigo" id="section-models">
    <div class="section-head"><div class="section-line"></div><span class="section-label">大模型动态（全天汇总）</span><span class="section-label-cn">Models</span></div>
    <div class="feature-card"><div class="card-row"><div class="card-body">
      <div class="card-tag" style="color:#6366f1;">HEADLINE</div>
      <div class="card-title">Claude Code 渗透微软内部：$300 亿 Azure 交易 + MCP 交互式应用</div>
      <div class="card-desc">The Verge 独家报道：Claude Code 正被微软最大工程团队全面采用，甚至鼓励非开发者使用。微软已成为 Anthropic 最大客户之一（$300 亿 Azure 算力交易）。同期 Anthropic 发布 MCP Apps 扩展——用户可在 Claude 聊天界面内直接操作 Slack、Figma、Canva、Asana 等应用，不再只是文本响应。The Verge 评论：这意味着 Claude 正在从"对话工具"进化为"工作台操作系统"。</div>
      <div class="card-meta"><span>The Verge</span><span>&#183;</span><span>6月</span><span>&#183;</span><span class="card-meta-link">独家报道</span></div>
      <div style="margin-top:8px; font-size:9px; color:#a5b4fc;">💡 开发者影响：MCP 生态从"工具调用"升级为"应用交互"，Claude 正成为新的工作入口</div>
      <a href="https://www.theverge.com/tech/865689/microsoft-claude-code-anthropic-partnership-notepad" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a>
    </div><div class="card-icon">&#9889;</div></div></div>
    <div class="sub-grid">
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">OpenAI · The Verge</div><div class="sub-title">OpenAI 高管大洗牌：Greg Brockman 统管产品，整合 ChatGPT+Codex 冲刺 IPO</div><div class="sub-desc">The Verge 报道：OpenAI 持续重组高管层以赢得 AI Agent 之战。Greg Brockman 正式统管所有产品线，将 ChatGPT 和 Codex 合并为"单一 Agent 平台"，砍掉多个"副线项目"，为下半年潜在 IPO 做准备。战略焦点明确：编程 + 企业。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">The Verge · 6月</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：OpenAI IPO 意味着更透明的定价和路线图，但也可能加速商业化</div><a href="https://www.theverge.com/ai-artificial-intelligence/931544/openai-keeps-shuffling-its-executives-in-bid-to-win-ai-agent-battle" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">微软 Build · 36氪</div><div class="sub-title">微软 7 款 MAI 模型 + Scout Agent + Project Solara：PC 变 AI 工位</div><div class="sub-desc">MAI-Thinking-1（35B 活跃/1T 总参数/256K 上下文）从零训练不蒸馏；Surface RTX Spark Dev Box 提供 1 PFLOPS 本地算力；Microsoft Scout 基于 OpenClaw 做常驻个人助理（能打电话）；Project Solara 是专为 AI Agent 设计的安卓系统。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">36氪/The Verge · 6月3日</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：微软从 OpenAI 分销商变成全栈竞争者——自研模型+芯片+AgentOS</div><a href="https://www.36kr.com/p/3836668626891910" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">苹果 · The Verge</div><div class="sub-title">Siri 变身 ChatGPT 式聊天机器人："Campos" 计划 + Gemini 定制模型</div><div class="sub-desc">苹果 Siri 全面重构——代号"Campos"，从语音助手升级为 ChatGPT 式聊天机器人（输入+语音双模式）。底层使用 Google 定制 Gemini 模型，WWDC 2026 公布、iOS 27/macOS 27 正式上线。The Verge 评论：苹果终于承认自研模型不足以独立支撑 AI 体验。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">The Verge · 1月/6月</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：iOS 27 将开放 Siri AI 给开发者，新的 App Intents 框架值得关注</div><a href="https://www.theverge.com/news/865172/apple-siri-ai-chatbot-chatgpt" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">字节 · 36氪</div><div class="sub-title">2026 字节 AI 四个关键命题：世界模型、Seedance、Coding、豆包商业化</div><div class="sub-desc">36氪独家梳理：字节 AI 2026 年聚焦四大方向——世界模型（具身智能基础设施）、Seedance 视频生成（2.0 已发布）、Coding 地基（豆包专业版对标 Codex）、豆包商业化（DAU 破亿后的变现压力）。火山引擎同步进军汽车 AI 座舱。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">36氪 · 6月3日</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：豆包生态开放度决定开发者的接入价值，Seedance API 值得关注</div><a href="https://36kr.com/newsflashes/3838463320869128" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-green" id="section-tools">
    <div class="section-head"><div class="section-line"></div><span class="section-label">工具 & 部署</span><span class="section-label-cn">Tools & Deploy</span></div>
    <div class="tool-row">
      <div class="tool-card"><div class="tool-icon">&#128268;</div><div class="tool-name">Claude MCP Apps</div><div class="tool-desc">Anthropic 发布 MCP 交互式扩展：用户可在 Claude 聊天界面直接操作 Slack/Figma/Canva/Asana。从"文本响应"升级为"应用内操作"。</div><span class="tool-badge badge-new">新范式</span><a href="https://www.theverge.com/news/867673/claude-mcp-app-interactive-slack-figma-canva" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="tool-card"><div class="tool-icon">&#128187;</div><div class="tool-name">国产 AI PC 抢跑</div><div class="tool-desc">长城 N90 Pro 搭载后摩智能 M50 存算一体芯片，10W 功耗本地运行 35B 大模型。2026 被定义为"Agent PC 元年"，端侧推理零边际成本。</div><span class="tool-badge badge-new">国产芯片</span><a href="https://36kr.com/p/3844312272390403" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="tool-card"><div class="tool-icon">&#128737;</div><div class="tool-name">NanoClaw+JFrog</div><div class="tool-desc">AI Agent 供应链"免疫系统"：拦截恶意 MCP 包，自动引导到安全版本。开源免费，解决 Agent 自动下载包的安全隐患。</div><span class="tool-badge badge-new">安全</span><a href="https://venturebeat.com/security/nanoclaw-and-jfrog-launch-immune-system-to-block-ai-agents-from-downloading-malicious-code" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-amber" id="section-policy">
    <div class="section-head"><div class="section-line"></div><span class="section-label">政策 & 合规</span><span class="section-label-cn">Policy & Compliance</span></div>
    <div class="sub-grid">
      <div class="sub-card"><div class="sub-tag" style="color:#fcd34d;">国家战略 · 5月</div><div class="sub-title">三部门联合印发智能体实施意见：四层安全防护 + 19 个典型场景</div><div class="sub-desc">国家网信办、发改委、工信部首次在国家层面定义"智能体"。赛迪研究院钟新龙解读四层防护：外约束（行为围栏）+ 内嵌入（权限管理）+ 供应链（防数据投毒）+ 软法（区块链可追溯）。AI 终端智能化分级 L1-L4 国标同步启动。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">人民网 · 5月-6月</div><div style="margin-top:4px; font-size:8px; color:#fcd34d;">💡 开发者影响：智能体从概念进入法律框架，安全评估和算法备案是上线前置条件</div><a href="http://society.people.com.cn/n1/2026/0516/c1008-40720964.html" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#fcd34d;">全球治理 · 6月15日</div><div class="sub-title">AI 终端分级 L1-L4 国标启动 + 商务部筹划"AI+消费"政策</div><div class="sub-desc">工信部启动 AI 终端智能化分级国标（L1-L4）。商务部筹划"AI+消费"政策体系，严格规制大数据杀熟与诱导性消费行为。经济日报评论：打开"AI+消费"想象空间的同时须守住安全底线。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">经济日报/人民网 · 6月15日</div><div style="margin-top:4px; font-size:8px; color:#fcd34d;">💡 开发者影响：终端上市须通过分级认证，"AI+消费"合规要求即将明确</div><a href="http://theory.people.com.cn/n1/2026/0615/c40531-40740229.html" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-cyan" id="section-cases">
    <div class="section-head"><div class="section-line"></div><span class="section-label">应用落地</span><span class="section-label-cn">Real-World AI</span></div>
    <div class="dual-cards">
      <div class="rank-card"><div class="rank-label" style="color:#67e8f9;">&#127981; 演变路线 · 36氪</div><div style="font-size:14px; font-weight:500; color:var(--text-primary); margin-bottom:6px;">大厂 Agent 之争沿四条主线演变：生产力、产品打通、生态、上下文</div><div style="font-size:10px; color:var(--text-secondary); line-height:1.5; margin-bottom:8px;">36氪深度分析：中国大厂 Agent 竞争正沿四条主线展开——①拓展生产力场景用户（微软 Scout/OpenAI Codex/豆包专业版）；②深度打通内部产品（千问整合外卖打车淘宝、微信 Agent 调度小程序）；③建立 Skill/Agent 生态（千问开放第三方 Skill、微信 Agent 原型测试）；④积累上下文（AI 产品需连接多源上下文信息才能形成壁垒）。</div><div style="font-size:8px; color:var(--text-tertiary);">36氪 · 6月7日</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 开发者影响：四条主线对应四种开发者机会——插件、小程序、Skill、数据连接器</div><a href="https://36kr.com/p/3843690773367296" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="rank-card"><div class="rank-label" style="color:#67e8f9;">&#127917; 内容 Agent · 36氪</div><div style="font-size:14px; font-weight:500; color:var(--text-primary); margin-bottom:6px;">字节小云雀 vs 阿里万镜一刻：内容 Agent 一番战的胜负手</div><div style="font-size:10px; color:var(--text-secondary); line-height:1.5; margin-bottom:8px;">字节小云雀（Seedance 2.0，DAU 超 80 万，免费为抖音供内容）vs 阿里万镜一刻（HappyHorse+Wan 2.7，流程化资产管理）。36氪评论：除字节外其他家做影视内容 Agent 都是"吃力不讨好"——字节的闭环生态（生产→分发→消费全自有）是决定性优势。</div><div style="font-size:8px; color:var(--text-tertiary);">36氪 · 6月12日</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 开发者影响：内容 Agent 赛道字节生态占优，阿里侧适合企业级素材管理场景</div><a href="https://www.36kr.com/p/3850041320543490" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-amber" id="section-oss">
    <div class="section-head"><div class="section-line"></div><span class="section-label">开源热度（全天 Top10）</span><span class="section-label-cn">Open Source Pulse</span></div>
    <div class="dual-cards">
      <div class="rank-card"><div class="rank-label" style="color:#fcd34d;">&#128200; GitHub Trending — AI Top 10（W24）</div>
        <div class="rank-row"><span class="rank-num">1</span><span class="rank-name">mvanhorn/last30days-skill</span><span class="rank-stat rank-up">+12K/周</span></div><div class="rank-row"><span class="rank-num">2</span><span class="rank-name">chopratejas/headroom</span><span class="rank-stat rank-up">+10K/周</span></div><div class="rank-row"><span class="rank-num">3</span><span class="rank-name">Leonxlnx/taste-skill</span><span class="rank-stat rank-up">+8.7K/周</span></div><div class="rank-row"><span class="rank-num">4</span><span class="rank-name">addyosmani/agent-skills</span><span class="rank-stat rank-up">+8.3K/周</span></div><div class="rank-row"><span class="rank-num">5</span><span class="rank-name">apple/container</span><span class="rank-stat rank-up">+7.8K/周</span></div>
        <div class="rank-row"><span class="rank-num">6</span><span class="rank-name">microsoft/markitdown</span><span class="rank-stat rank-up">152K总★</span></div><div class="rank-row"><span class="rank-num">7</span><span class="rank-name">NVIDIA/SkillSpector</span><span class="rank-stat rank-up">+2.6K/周</span></div><div class="rank-row"><span class="rank-num">8</span><span class="rank-name">CopilotKit/CopilotKit</span><span class="rank-stat rank-up">+2.5K/周</span></div><div class="rank-row"><span class="rank-num">9</span><span class="rank-name">Panniantong/Agent-Reach</span><span class="rank-stat rank-up">+5.4K/周</span></div><div class="rank-row"><span class="rank-num">10</span><span class="rank-name">roboflow/supervision</span><span class="rank-stat rank-up">+4K/周</span></div>
        <a href="https://github.com/trending?since=weekly" class="read-original" target="_blank" rel="noopener">查看完整榜单 <span class="read-original-arrow">→</span></a></div>
      <div class="rank-card"><div class="rank-label" style="color:#fcd34d;">&#128200; 趋势解读（W24）</div><div style="font-size:10px; color:var(--text-secondary); line-height:1.6;"><p><strong>Claude Skills 占据半壁江山</strong> Top10 中 4 个 Skills 项目。mattpocock/skills 月增 48K★，Skills 模块化成为新范式。</p><p><strong>Token 压缩 + Agent 安全双主线</strong> headroom 省 60-95% Token；NVIDIA SkillSpector 检测 64 种漏洞；NanoClaw+JFrog 拦截恶意包。</p><p><strong>大厂全面入局开源</strong> 苹果 container、微软 markitdown 152K★、英伟达 Agent Toolkit 17 家采用。Linux 基金会接管 Goose。</p><p style="margin-top:6px; color:#fcd34d;">💡 18 个项目周增 87K★——AI 开源正从"模型开源"进入"Agent 基础设施开源"时代</p></div></div>
    </div>
  </div>
  <div class="section-gap section-cyan" id="section-overseas">
    <div class="section-head"><div class="section-line"></div><span class="section-label">海外参考</span><span class="section-label-cn">Global Brief</span></div>
    <div class="sub-grid">
      <div class="sub-card"><div class="sub-tag" style="color:#67e8f9;">🌏 Google I/O · The Verge</div><div class="sub-title">Gemini Spark：关掉电脑也运行的 24/7 AI Agent，能扫信用卡账单找隐藏费用</div><div class="sub-desc">Google I/O 2026 发布 Gemini Spark——常驻 AI Agent，关掉电脑后仍可 24/7 执行任务。能创建学习指南、从会议纪要生成待办、扫描信用卡账单找隐藏费用。接入 Canva/OpenTable/Instacart/Spotify/Expedia 等第三方服务。Gemini 3.5 Flash 成为默认模型，3.5 Pro 6 月发布。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">The Verge · 5月</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 开发者影响：常驻 Agent 需要新的隐私设计——你的数据就是 AI 的燃料</div><a href="https://www.theverge.com/tech/934172/google-io-gemini-ai-trust-personal-data" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#67e8f9;">💬 行业风向 · The Verge</div><div class="sub-title">Nadella 博客定调 2026："AI 的关键一年"，Agent 将取代传统 Office 工作流</div><div class="sub-desc">微软 CEO 罕见亲自写博客：2026 是"AI 的关键一年"，行业必须超越"AI slop vs 精致"之争。微软正押注 AI Agent 替代传统 Office/Windows 工作流。Office 全线免费 Agent Mode 已对全部 Microsoft 365 用户开放。用户可在 Excel 中切换 Anthropic 和 OpenAI 推理模型。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">The Verge · 6月</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 开发者影响：Office Agent 化意味着每个白领的工作流都将被 AI 重构</div><a href="https://www.theverge.com/news/852630/microsoft-ceo-satya-nadella-scratchpad-blog-ai-slop-comments" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#67e8f9;">🏛️ 微软+Anthropic · The Verge</div><div class="sub-title">微软与 OpenAI 独家合作终结，CEO 首次承认"自研 MAI 不再依赖第三方"</div><div class="sub-desc">2026 年 4 月微软与 OpenAI 正式结束独家合作关系。CEO Satya Nadella 首次公开承认 MAI-Thinking-1 从零训练、未蒸馏任何第三方模型。与此同时，微软成为 Anthropic 最大客户之一，Claude Code 在内部被广泛采用。The Verge：全球最大的软件公司正在从"AI 分销商"变成"AI 全栈竞争者"。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">The Verge · 4-6月</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 开发者影响：微软同时押注自研+Anthropic+OpenAI，多云多模型是明智策略</div><a href="https://www.theverge.com/tech/941664/microsoft-ai-model-reasoning-mai-thinking-1-build-2026" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>'''

start = html.find('<div class="section-gap section-indigo" id="section-models">')
end = html.find('<footer class="footer">')
html = html[:start] + c + '\n' + html[end:]

now = datetime.datetime.now()
html = re.sub(r'<span class="hero-badge-text" id="editionLabel">.*?</span>', f'<span class="hero-badge-text" id="editionLabel">晚间版 &#183; {now.strftime("%H:%M")} &#183; 全天汇总</span>', html)
html = re.sub(r'<p class="hero-date" id="dateLabel">.*?</p>', f'<p class="hero-date" id="dateLabel">{now.strftime("%Y年%m月%d日")} &#183; 星期一</p>', html)
html = re.sub(r'<p class="hero-updated" id="updatedLabel">.*?</p>', f'<p class="hero-updated" id="updatedLabel"><span class="hero-updated-dot"></span> 最后更新: {now.strftime("%Y-%m-%d %H:%M")} CST</p>', html)
tl = 'Claude Code渗透微软内部$300亿Azure交易+MCP交互式应用进化工作台OS；OpenAI高管大洗牌Brockman统管产品冲刺IPO；微软7款MAI模型+Scout Agent+Project Solara；苹果Siri重构为ChatGPT式聊天机器人；字节AI四个关键命题世界模型+Seedance+Coding+豆包商业化；国产AI PC长城N90 Pro存算一体10W跑35B；大厂Agent之争沿四条主线演变；Google Gemini Spark 24/7常驻Agent关电脑也运行。'
html = re.sub(r'<span class="tldr-text" id="tldrContent">.*?</span>', f'<span class="tldr-text" id="tldrContent">{tl}</span>', html, flags=re.DOTALL)

with open('archive/2026-06-15-evening.html', 'w', encoding='utf-8') as f: f.write(html)
ph = html.count('"#" class="read-original')
print(f'Built: {len(html)}B | Placeholders: {ph}')
