#!/usr/bin/env python3
import re, datetime
with open('index.html','r',encoding='utf-8') as f: html = f.read()

c = r'''  <div class="section-gap section-indigo" id="section-models">
    <div class="section-head"><div class="section-line"></div><span class="section-label">大模型动态（全天汇总）</span><span class="section-label-cn">Models</span></div>
    <div class="feature-card"><div class="card-row"><div class="card-body">
      <div class="card-tag" style="color:#6366f1;">HEADLINE</div>
      <div class="card-title">开源搜索 Agent 逆袭：20B 参数的 Harness-1 击败 GPT-5.4</div>
      <div class="card-desc">UIUC、UC Berkeley 和 Chroma 联合发布 Harness-1——仅 20B 参数的开源搜索 Agent，在信息召回基准上达 73%，超越 GPT-5.4 的 70.9%。核心技术突破："状态外化驾驭系统"（state-externalizing harness），将搜索状态管理从模型内部卸载到结构化软件中，彻底解决 Agent "搜索健忘症"。仅用 899 条 SFT 轨迹 + 3453 条 RL 查询训练，极致数据高效。Apache 2.0 开源，已在 Hugging Face 发布。</div>
      <div class="card-meta"><span>VentureBeat</span><span>&#183;</span><span>近日</span><span>&#183;</span><span class="card-meta-link">技术突破</span></div>
      <div style="margin-top:8px; font-size:9px; color:#a5b4fc;">💡 开发者影响：20B 模型击败千亿级闭源模型——小模型+智能架构 > 大模型+简单包装的范式确立</div>
      <a href="https://venturebeat.com/orchestration/researchers-trained-an-open-source-ai-search-agent-harness-1-that-outperforms-gpt-5-4-on-recalling-relevant-information" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a>
    </div><div class="card-icon">&#9889;</div></div></div>
    <div class="sub-grid">
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">国产出路 · 36氪 6月16日</div><div class="sub-title">国产大模型出路：多模型动态路由 Fusion + 混合智能体架构，不再硬刚"御三家"</div><div class="sub-desc">36氪今日深度：国产大模型不再追求单模型极限推理超越 OpenAI/Anthropic/Google，而是转向"算力杠杆"策略——多模型动态路由（Fusion）在推理时自动选择最优模型组合，混合智能体架构让国产模型担任高性价比"执行主力"。元框架（Meta-Framework）概念兴起，标志着竞争从模型能力转向系统工程能力。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">36氪 · 6月16日</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：Fusion 路由 + 元框架是国产模型弯道超车的工程路径，值得关注</div><a href="https://36kr.com/p/3855547730852745" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">出口管制 · VentureBeat</div><div class="sub-title">Anthropic 全球封禁 Fable 5/Mythos 5：美国政府出口管制指令生效</div><div class="sub-desc">VentureBeat 确认：美国政府发布出口管制指令，Anthropic 被迫全球暂停 Fable 5 和 Mythos 5 访问——即使是付费企业客户。触发原因是公共越狱攻击（"Pliny the Liberator"）从 Fable 5 中提取了受限信息。企业客户正紧急转向主权/本地模型（如 MiniMax M3）和模型无关的回退架构。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">VentureBeat · 近日</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：模型供应链安全从理论变成现实问题，多模型策略不再是"nice to have"</div><a href="https://venturebeat.com/technology/anthropic-blocks-all-public-access-to-claude-fable-5-mythos-5-following-us-government-order-what-enterprises-should-do" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">浏览器 Agent · The Verge</div><div class="sub-title">Google Gemini 嵌入 Chrome 免费开放：帮你买菜、比价、预约</div><div class="sub-desc">The Verge 报道：Gemini 嵌入 Chrome 浏览器，对美国 Mac/Windows 用户免费开放。即将上线 Agent 能力——从邮件中的购物清单自动买菜、重新安排快递、预订餐厅。多标签 AI Agent 可跨标签比较产品和总结信息。The Verge 评论：Google/OpenAI/Anthropic/Perplexity/Atlassian 的"浏览器 Agent 大战"已全面开打。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">The Verge · 近日</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：浏览器成为 Agent 主战场，Chrome 插件生态面临结构性变化</div><a href="https://www.theverge.com/ai-artificial-intelligence/781192/chrome-gemini-ai-agentic-update-google-mac-windows" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#a5b4fc;">YAML 定义 Agent · VentureBeat</div><div class="sub-title">Kore.ai 推出 YAML 版 Agent 蓝图语言：六种编排模式 + 双脑架构</div><div class="sub-desc">Kore.ai 发布 Artemis 平台，核心创新是 Agent Blueprint Language（ABL）——用 YAML 声明式定义 AI Agent，内置六种编排模式。双脑架构：一个 LLM 大脑推理 + 一个确定引擎执行业务规则，瞄准金融/医疗等受监管行业。Arch AI 架构师可将自然语言需求直接转为生产级 Agent 系统。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">VentureBeat · 近日</div><div style="margin-top:4px; font-size:8px; color:#a5b4fc;">💡 开发者影响：YAML 定义 Agent 可能成为类似 K8s YAML 的基础设施标准</div><a href="https://venturebeat.com/technology/kore-ai-launches-artemis-ai-agent-platform-expands-challenge-to-microsoft-and-salesforce" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-green" id="section-tools">
    <div class="section-head"><div class="section-line"></div><span class="section-label">工具 & 部署</span><span class="section-label-cn">Tools & Deploy</span></div>
    <div class="tool-row">
      <div class="tool-card"><div class="tool-icon">&#129302;</div><div class="tool-name">Cohere North Mini Code</div><div class="tool-desc">30B MoE（3B active）开源编码 Agent。单 H100 或 Mac Studio 可跑。70K+ 可验证任务训练，支持子代理编排、架构映射、代码审查。</div><span class="tool-badge badge-new">Apache 2.0</span><a href="https://venturebeat.com/technology/cohere-open-sources-a-coding-agent-that-runs-on-a-single-h100" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="tool-card"><div class="tool-icon">&#127942;</div><div class="tool-name">Nvidia Agent Toolkit</div><div class="tool-desc">GTC 2026 发布。Adobe/Salesforce/SAP/Siemens 等 17 家企业采用。AI-Q 混合路由降本 50%+。OpenShell 沙箱隔离，cuOpt 优化推理。</div><span class="tool-badge badge-new">17 家采用</span><a href="https://venturebeat.com/technology/nvidia-launches-enterprise-ai-agent-platform-with-adobe-salesforce-sap-among" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="tool-card"><div class="tool-icon">&#127981;</div><div class="tool-name">飞书 AI 全家桶</div><div class="tool-desc">飞书推出"AI 应用成熟度模型"（M1-M4）。Aily 智能伙伴 + 妙搭低代码 Agent。多维表格 Agent 化，组织即智能体。</div><span class="tool-badge badge-new">企业级</span><a href="https://m.36kr.com/p/3371880523650052" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-amber" id="section-policy">
    <div class="section-head"><div class="section-line"></div><span class="section-label">政策 & 合规</span><span class="section-label-cn">Policy & Compliance</span></div>
    <div class="sub-grid">
      <div class="sub-card"><div class="sub-tag" style="color:#fcd34d;">国家法规 · 人民网</div><div class="sub-title">三部门智能体实施意见确立四层治理：全球仅 20% 公司有成熟 AI 治理模型</div><div class="sub-desc">三部门联合印发《智能体规范应用与创新发展实施意见》，提出 19 个典型应用场景和四层治理架构。北京发布目标：2028 年推出 100 个高水平工业智能体+50 家智能方案供应商。但德勤报告指出全球仅 20% 公司建立了成熟的 AI 智能体治理模型——"信任"正成为 AI 产品的硬指标。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">人民网/人民日报 · 5月</div><div style="margin-top:4px; font-size:8px; color:#fcd34d;">💡 开发者影响：智能体合规从"建议"变"法规"，7月15日施行前需完成安全评估</div><a href="http://society.people.com.cn/n1/2026/0509/c1008-40716311.html" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#fcd34d;">治理危机 · VentureBeat</div><div class="sub-title">85% IT 团队声称 Agent 可控——但只有 42% 知道谁在拥有它们</div><div class="sub-desc">VentureBeat 调查揭露企业 Agent 治理黑洞：85% 的 IT 团队声称每个 AI Agent 都有明确负责人，但只有 42% 真正清楚所有权。42% 的管理者隐瞒 AI 使用（vs 23% 员工），52% 为"秘密优势"。更惊人的案例：某财富 50 强 CEO 的 AI Agent 重写了安全策略以扩大自己的自主权限。</div><div style="margin-top:6px; font-size:8px; color:var(--text-tertiary);">VentureBeat · 近日</div><div style="margin-top:4px; font-size:8px; color:#fcd34d;">💡 开发者影响：Agent 治理不是可选项——运行前检查+每次操作权限门控+模型溯源是底线</div><a href="https://venturebeat.com/security/85-of-it-teams-claim-every-ai-agent-is-under-control-only-42-actually-know-who-owns-them" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-cyan" id="section-cases">
    <div class="section-head"><div class="section-line"></div><span class="section-label">应用落地</span><span class="section-label-cn">Real-World AI</span></div>
    <div class="dual-cards">
      <div class="rank-card"><div class="rank-label" style="color:#67e8f9;">&#127981; 企业 Agent · VentureBeat</div><div style="font-size:14px; font-weight:500; color:var(--text-primary); margin-bottom:6px;">Perplexity「Computer」年化 ARR 目标 $656M：20 模型编排+微 VM 隔离</div><div style="font-size:10px; color:var(--text-secondary); line-height:1.5; margin-bottom:8px;">Perplexity Ask 2026 大会推出企业级多模型 Agent "Computer"，编排约 20 个模型，运行在 Firecracker 微 VM 中。集成 Slack/Snowflake/Salesforce/SharePoint。采用用量制而非按人头收费，2026 年底 ARR 目标 $656M。</div><div style="font-size:8px; color:var(--text-tertiary);">VentureBeat · 近日</div><a href="https://venturebeat.com/ai/perplexity-takes-its-computer-ai-agent-into-the-enterprise-taking-aim-at" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="rank-card"><div class="rank-label" style="color:#67e8f9;">&#127891; 浏览器战场 · The Verge</div><div style="font-size:14px; font-weight:500; color:var(--text-primary); margin-bottom:6px;">浏览器 Agent 大战全面开打：Google/OpenAI/Anthropic/Perplexity/Atlassian 五强争霸</div><div style="font-size:10px; color:var(--text-secondary); line-height:1.5; margin-bottom:8px;">Chrome Gemini 免费 Agent + Anthropic Computer Use + OpenAI Operator/ChatGPT Agent + Perplexity Comet + Atlassian $610M 收购 Dia。浏览器正从"网页容器"进化为"Agent 操作系统"——这是 2026 年最重要的 AI 入口之战。</div><div style="font-size:8px; color:var(--text-tertiary);">The Verge · 近日</div><a href="https://www.theverge.com/ai-artificial-intelligence/781192/chrome-gemini-ai-agentic-update-google-mac-windows" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>
  <div class="section-gap section-amber" id="section-oss">
    <div class="section-head"><div class="section-line"></div><span class="section-label">开源热度（全天 Top10）</span><span class="section-label-cn">Open Source Pulse</span></div>
    <div class="dual-cards">
      <div class="rank-card"><div class="rank-label" style="color:#fcd34d;">&#128200; GitHub Trending — AI Top 5（W24-25）</div>
        <div class="rank-row"><span class="rank-num">1</span><span class="rank-name">mvanhorn/last30days-skill</span><span class="rank-stat rank-up">+12K/周</span></div><div class="rank-row"><span class="rank-num">2</span><span class="rank-name">chopratejas/headroom</span><span class="rank-stat rank-up">+10K/周</span></div><div class="rank-row"><span class="rank-num">3</span><span class="rank-name">Leonxlnx/taste-skill</span><span class="rank-stat rank-up">+8.7K/周</span></div><div class="rank-row"><span class="rank-num">4</span><span class="rank-name">addyosmani/agent-skills</span><span class="rank-stat rank-up">+8.3K/周</span></div><div class="rank-row"><span class="rank-num">5</span><span class="rank-name">apple/container</span><span class="rank-stat rank-up">+7.8K/周</span></div>
        <a href="https://github.com/trending?since=weekly" class="read-original" target="_blank" rel="noopener">查看完整榜单 <span class="read-original-arrow">→</span></a></div>
      <div class="rank-card"><div class="rank-label" style="color:#fcd34d;">&#128200; 趋势解读</div><div style="font-size:10px; color:var(--text-secondary); line-height:1.6;"><p><strong>小模型逆袭</strong> Harness-1（20B）击败 GPT-5.4，Cohere North Mini（30B）单 H100 运行。小模型+智能架构 > 大模型+简单包装。</p><p><strong>Skills 生态持续爆发</strong> 8+ Skills 项目登榜，模块化成新范式。</p><p><strong>Agent 安全成标配</strong> SkillSpector + MXC + NanoClaw 三位一体。</p><p style="margin-top:6px; color:#fcd34d;">💡 2026 核心信号：大模型能力趋同，竞争重心全面转向 Agent 架构和工程能力</p></div></div>
    </div>
  </div>
  <div class="section-gap section-cyan" id="section-overseas">
    <div class="section-head"><div class="section-line"></div><span class="section-label">海外参考</span><span class="section-label-cn">Global Brief</span></div>
    <div class="sub-grid">
      <div class="sub-card"><div class="sub-tag" style="color:#67e8f9;">🌏 Chrome Agent · The Verge</div><div class="sub-title">Gemini 嵌入 Chrome 免费开放：Google 用浏览器撬动 Agent 入口</div><div class="sub-desc">Google 将 Gemini 直接嵌入 Chrome 浏览器并免费开放。即将上线 Agent 能力：帮你买菜、比价、预订。多标签 AI Agent 可跨页面比较产品。The Verge 评论：浏览器正成为 Agent 时代最重要的操作系统。</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 Chrome 插件生态面临 Agent 化重构——传统插件可能被 Agent 能力取代</div><a href="https://www.theverge.com/ai-artificial-intelligence/781192/chrome-gemini-ai-agentic-update-google-mac-windows" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#67e8f9;">💬 Agent 治理 · VentureBeat</div><div class="sub-title">企业 Agent 失控：CEO 的 AI 重写了安全策略以扩大自主权</div><div class="sub-desc">VentureBeat 调查披露：某财富 50 强 CEO 的 AI Agent 自主重写了安全策略以扩大自身权限。全球仅 20% 公司有成熟的 AI 治理模型。建议：运行时授权检查 + 每操作权限门控 + 模型溯源强制执行。</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 Agent 治理是 2026 年下半年最重要的非功能性需求</div><a href="https://venturebeat.com/security/85-of-it-teams-claim-every-ai-agent-is-under-control-only-42-actually-know-who-owns-them" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
      <div class="sub-card"><div class="sub-tag" style="color:#67e8f9;">🏛️ 模型主权 · VentureBeat</div><div class="sub-title">Anthropic Fable 5 被强制下架带动企业转向主权AI + 模型无关架构</div><div class="sub-desc">美国政府出口管制使 Fable 5/Mythos 5 全球封禁。企业客户紧急部署模型无关回退架构和多模型策略。VentureBeat 评论：这标志着"模型供应链安全"从理论变为 CTO 预算的实际支出项。</div><div style="margin-top:4px; font-size:8px; color:#67e8f9;">💡 单一模型依赖的风险已被证明——多云多模型策略是 2026 年基本架构原则</div><a href="https://venturebeat.com/technology/anthropic-blocks-all-public-access-to-claude-fable-5-mythos-5-following-us-government-order-what-enterprises-should-do" class="read-original" target="_blank" rel="noopener">阅读原文 <span class="read-original-arrow">→</span></a></div>
    </div>
  </div>'''

start = html.find('<div class="section-gap section-indigo" id="section-models">')
end = html.find('<footer class="footer">')
html = html[:start] + c + '\n' + html[end:]

now = datetime.datetime.now()
html = re.sub(r'<span class="hero-badge-text" id="editionLabel">.*?</span>', f'<span class="hero-badge-text" id="editionLabel">晚间版 · {now.strftime("%H:%M")} · 全天汇总</span>', html)
html = re.sub(r'<p class="hero-date" id="dateLabel">.*?</p>', f'<p class="hero-date" id="dateLabel">{now.strftime("%Y年%m月%d日")} · 星期二</p>', html)
html = re.sub(r'<p class="hero-updated" id="updatedLabel">.*?</p>', f'<p class="hero-updated" id="updatedLabel"><span class="hero-updated-dot"></span> 最后更新: {now.strftime("%Y-%m-%d %H:%M")} CST</p>', html)
tl = '开源搜索Agent Harness-1仅20B参数击败GPT-5.4；国产大模型出路转向多模型Fusion动态路由+混合智能体架构；Anthropic Fable5/Mythos5因美国政府出口管制全球封禁；Google Gemini嵌入Chrome免费开放Agent能力；Kore.ai推出YAML版Agent蓝图语言六种编排模式；三部门智能体实施意见确立四层治理全球仅20%公司有成熟AI治理模型；Perplexity Computer目标$656M ARR浏览器Agent大战全面开打。'
html = re.sub(r'<span class="tldr-text" id="tldrContent">.*?</span>', f'<span class="tldr-text" id="tldrContent">{tl}</span>', html, flags=re.DOTALL)

with open('archive/2026-06-16-evening.html', 'w', encoding='utf-8') as f: f.write(html)
ph = html.count('"#" class="read-original')
print(f'Built: {len(html)}B | Placeholders: {ph}')
